language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
before_install:
    - "pip install -r requirements.txt"
    - "pip install -r requirements_dev.txt"
script:
    - "make test"
notifications:
    email:
        recipients:
            - "ellisonleao@gmail.com"
addons:
    code_climate:
        repo_token: adcbe842235cb3d400a4e9fd2b97c745439d2c05f05dd46345fe3da3bf51e0ea
